#+title: Nginx

* Contenuti :TOC:
- [[#configurazione-web-server][Configurazione web server]]
- [[#container-image][Container image]]
  - [[#dockerfile][Dockerfile]]

* Configurazione web server

* Container image
Una container image è un package di software eseguibile, leggero ed isolato che include tutto il necessario per eseguire il suo compito, in questo caso svolge la funzione di web server.

Le container image diventano container quando vengono eseguite dal *docker engine* tramite CLI o interfaccia grafica.

Una soluzione alternativa ai container è la virtualizzazione.
Non ho optato per la virtualizzazione semplicemente perchè è molto comodo gestire i 3 diversi container tramite docker-compose da CLI.
Inoltre i container offrono performance miglori sfruttando il kernel della macchina host, ma questo nel contesto cloud è secondario.

** Dockerfile
La base container image utilizzata è quella ufficiale di nginx reperibile sul sito web [[https://hub.docker.com/_/nginx?tab=description][hub.docker.com]].
Per preferenza personale utilizzo il tag *stable-alpine* per usufruire della versione stable di nginx e per il ridotto numero di package preinstallati da alpine.

#+begin_src dockerfile
FROM nginx:stable-alpine
#+end_src
