version: '3'
services:
  web:
    build: ./web/
    ports:
      - "80:80"
    volumes:
      - ../www:/var/www/html

  app:
    build: ./bll/
    volumes:
      - ../www:/var/www/html

  db:
    image: "mariadb"
    environment:
      MARIADB_USER: "root"
      MARIADB_ROOT_PASSWORD: "root"
